name: restler
description: A beautiful and powerful REST client app for Android.
publish_to: "none"

version: 1.0.0+78

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
